#!/bin/sh

##########
# Warning: If you update this file, you must copy to crond.d manually 
# pm2 must be installed globally by unikname user.
##########

*/30 7-9,12-16 * * MON-FRI ubuntu /home/ubuntu/uns-core/scripts/upstream/update-upstream.sh >> /home/ubuntu/cron-uns-core-update.log 2>&1
