#!/bin/sh

##########
# Warning: If you update this file, you must copy to crond.d manually 
##########

*/30 7-9,12-16 * * MON-FRI unikname /home/unikname/core/scripts/upstream/update-upstream.sh >> /home/unikname/cron-uns-core-update.log
