version: '2'
services:
  forger:
    image: universalnamesystem/dcore:latest
    restart: always
    environment:
      UNS_NET: dalinet
      CORE_DB_HOST: postgres
      CORE_DB_PORT: 5432
      CORE_DB_PASSWORD: password
      CORE_DB_USER: uns
      CORE_API_RATE_LIMIT: false
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    networks:
      - core
    tty: true
